FROM openjdk:11
LABEL maintainer="shchoi<shchoi@iei.or.kr>"
LABEL version="1.0"
# /root 디렉터리에 05_SpringBoot_MVC-0.0.1-SNAPSHOT.jar 파일을 복사
ADD 05_SpringBoot_MVC-0.0.1-SNAPSHOT.jar /root
ENV TZ = Asia/Seoul
EXPOSE 8088
# 작업 디렉터리를 /root로 변경
WORKDIR /root
# 컨테이너 생성 시 05_SpringBoot_MVC-0.0.1-SNAPSHOT.jar 파일을 자동으로 실행 
CMD ["java", "-jar", "05_SpringBoot_MVC-0.0.1-SNAPSHOT.jar", "--srping.profiles.active=dev"]